import { useMemo, useState } from 'react';
import { Avatar, Brand, Icon, Modal } from './UI';
import { CallRoom, type Scenario } from './CallRoom';
import { people, selectPeople, formatDuration, type Person, type DemoProfile, type Filter, type Language } from './model';
import './prototype.css';
const initialProfile:DemoProfile={name:'Tony',native:'Spanish',language:'English'};
export default function PrototypeApp(){
 const [profile,setProfile]=useState(initialProfile);const [view,setView]=useState<'partners'|'sessions'|'profile'|'welcome'>('partners');
 const [filter,setFilter]=useState<Filter>('Everyone');const [query,setQuery]=useState('');const [topic,setTopic]=useState('All interests');const [blocked,setBlocked]=useState<number[]>([]);
 const [dialog,setDialog]=useState<'language'|'scenarios'|null>(null);const [selected,setSelected]=useState<Person|null>(null);const [call,setCall]=useState<{person:Person;incoming:boolean;scenario:Scenario}|null>(null);
 const [scenario,setScenario]=useState<Scenario>('normal');const [empty,setEmpty]=useState(false);const [offline,setOffline]=useState(false);const [toast,setToast]=useState('');
 const [sessions,setSessions]=useState<{name:string;seconds:number;id:number}[]>([]);
 const filtered=useMemo(()=>empty?[]:selectPeople(profile.language,filter,query,topic,blocked),[profile.language,filter,query,topic,blocked,empty]);
 const total=selectPeople(profile.language,'Everyone','','All interests',blocked).length;
 function notify(message:string){setToast(message);}
 function startCall(person:Person,incoming=false){setSelected(null);setCall({person,incoming,scenario});setToast('');}
 function reset(){setProfile(initialProfile);setView('partners');setFilter('Everyone');setQuery('');setTopic('All interests');setBlocked([]);setSessions([]);setEmpty(false);setOffline(false);setScenario('normal');setDialog(null);setCall(null);setToast('Demo reset. You’re ready for a fresh start.');}
 function changeLanguage(lang:Language){setProfile({...profile,language:lang});setFilter('Everyone');setQuery('');setTopic('All interests');setDialog(null);}
 const initials=profile.name.trim().split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase()||'T';
 return <div className="lc-prototype">
  <div className="demo-bar"><span><span className="demo-label">PROTOTYPE</span> Sample people. Simulated calls. Explore freely.</span><button onClick={()=>setDialog('scenarios')}>Test scenarios <Icon name="down" size={14}/></button></div>
  <div className="app-layout">
   <aside className="sidebar"><button className="brand-button" onClick={()=>{setView('partners');setCall(null);}} aria-label="LinguaConnect home"><Brand/></button><div className="sidebar-caption">A world of conversation.</div>
    <nav aria-label="Main navigation"><button className={view==='partners'&&!call?'selected':''} onClick={()=>{setCall(null);setView('partners');}}><Icon name="users"/> Find a partner</button><button className={view==='sessions'&&!call?'selected':''} onClick={()=>{setCall(null);setView('sessions');}}><Icon name="clock"/> My sessions {sessions.length>0&&<span className="nav-count">{sessions.length}</span>}</button><button className={view==='profile'&&!call?'selected':''} onClick={()=>{setCall(null);setView('profile');}}><Icon name="user"/> My profile</button></nav>
    <div className="sidebar-bottom"><div className="sidebar-tip"><Icon name="spark"/><strong>Progress starts with hello.</strong><p>A few minutes of conversation can make all the difference.</p></div><button className="account-button" onClick={()=>{setCall(null);setView('profile');}}><Avatar initials={initials} color="green"/><span><strong>{profile.name}</strong><small>Demo account</small></span><Icon name="down" size={17}/></button></div>
   </aside>
   <div className="workspace"><header className="workspace-header"><span className="breadcrumb">Your conversation space</span><div className="header-actions"><button className="language-switch" onClick={()=>setDialog('language')} disabled={!!call}><span className="lang-mini">{profile.language==='English'?'EN':'ES'}</span>Practicing {profile.language}<Icon name="down" size={15}/></button><Avatar initials={initials} color="green"/></div></header>
    {toast&&<div className="toast" role="status"><Icon name="check" size={18}/><span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setToast('')}><Icon name="close" size={16}/></button></div>}
    {call?<CallRoom key={`${call.person.id}-${call.incoming}`} person={call.person} language={profile.language} incoming={call.incoming} scenario={call.scenario} onClose={()=>setCall(null)} onFinish={(name,seconds)=>setSessions(prev=>[{name,seconds,id:Date.now()},...prev])}/>:view==='partners'?<main className="partners-page">
     <div className="page-heading"><div className="eyebrow">REAL CONNECTIONS. LITTLE BY LITTLE.</div><h1>Your next conversation<br/>starts with <em>hello.</em></h1><p>Find a friendly face. Practice {profile.language}. Be yourself.</p></div>
     <div className="main-columns"><section className="directory" aria-label="Practice partners"><div className="directory-heading"><h2>Find your conversation partner</h2><span className="count-label">{empty?0:total} sample profiles</span></div>
      <div className="search-row"><label className="search-input"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search partners" placeholder="Search name, city or interest…"/>{query&&<button className="icon-button" aria-label="Clear search" onClick={()=>setQuery('')}><Icon name="close" size={16}/></button>}</label><label className="interest-filter"><Icon name="globe" size={17}/><select aria-label="Filter by interest" value={topic} onChange={e=>setTopic(e.target.value)}>{['All interests','Travel','Culture','Food','Music','Books','Art','Coffee','Outdoors'].map(t=><option key={t}>{t}</option>)}</select></label></div>
      <div className="filter-tabs" role="group" aria-label="Partner type">{(['Everyone','Native speakers','Fellow learners'] as Filter[]).map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div>
      {offline?<div className="empty-state connection-empty"><Icon name="refresh" size={35}/><h3>You’re temporarily offline</h3><p>We’ll help you get back to your next conversation.</p><button className="primary" onClick={()=>{setOffline(false);notify('Connection restored in the demo.');}}>Reconnect</button></div>:filtered.length===0?<div className="empty-state"><Icon name="users" size={35}/><h3>{empty?'It’s quiet here right now.':'No partners found.'}</h3><p>{empty?'Come back soon or explore another language.':'Try a different name, interest, or partner type.'}</p><button className="secondary" onClick={()=>{setQuery('');setTopic('All interests');setFilter('Everyone');setEmpty(false);setBlocked([]);}}>Reset filters</button></div>:<div className="partner-grid">{filtered.map(p=><article className="partner-card" key={p.id}><div className="card-profile"><Avatar initials={p.initials} color={p.color}/><div><button className="person-name" onClick={()=>setSelected(p)}>{p.name}</button><p>{p.city}, {p.country}</p></div><span className="available-dot" title="Available in demo"/></div><div className="language-details"><span><span className="tiny-label">SPEAKS</span>{p.native}<small>Native</small></span><span><span className="tiny-label">PRACTICING</span>{profile.language}<small>{p.native===profile.language?'Conversation host':p.level}</small></span></div><div className="interest-tags">{p.interests.map(i=><button key={i} onClick={()=>setTopic(i)}>{i}</button>)}</div><div className="card-footer"><button className="text-button" onClick={()=>setSelected(p)}>View profile</button><button className="call-button" aria-label={`Call ${p.name}`} onClick={()=>startCall(p)}><Icon name="phone" size={16}/>Say hello</button></div></article>)}</div>}
      <p className="directory-footnote"><Icon name="shield" size={16}/> A welcoming space for every accent and every level.</p>
     </section><aside className="practice-aside"><div className="quick-match"><span className="section-kicker"><Icon name="shuffle" size={17}/> A LITTLE SPONTANEITY</span><h2>Skip the search.<br/>Start talking.</h2><p>We’ll pick a partner from your current selection.</p><div className="stacked-avatars">{filtered.slice(0,3).map(p=><Avatar key={p.id} initials={p.initials} color={p.color}/>)}<span>{filtered.length>0?`${filtered.length} to choose from`:'More conversations soon'}</span></div><button className="coral-button" disabled={filtered.length===0||offline} onClick={()=>startCall(filtered[Math.floor(Math.random()*filtered.length)])}>Find me a partner <Icon name="arrow" size={18}/></button><small>One voice call. Endless possibilities.</small></div>
      <div className="session-note"><span className="note-icon"><Icon name="mic" size={21}/></span><div className="eyebrow">MAKE IT A GOOD CONVERSATION</div><h3>A little nervous?<br/>You’re in good company.</h3><p>Start with where you’re from. Ask about their day. The words will follow.</p><div className="note-divider"/><span><Icon name="clock" size={16}/> Even 5 minutes is a good start.</span></div>
      <button className="onboarding-link" onClick={()=>setView('welcome')}>Try the welcome experience <Icon name="arrow" size={17}/></button>
     </aside></div>
    </main>:view==='profile'?<main className="simple-page"><div className="eyebrow">YOUR CORNER OF THE WORLD</div><h1>Make yourself at home.</h1><p className="muted">Your demo profile is only kept for this open session.</p><ProfileForm profile={profile} onSave={p=>{setProfile(p);setFilter('Everyone');notify('Your demo profile has been updated.');}}/><section className="settings-card"><h2>Demo preferences</h2><p>{blocked.length} sample {blocked.length===1?'profile':'profiles'} hidden from your partner list.</p><button className="secondary" onClick={()=>{setBlocked([]);notify('All sample profiles are visible again.');}} disabled={!blocked.length}>Restore hidden profiles</button><button className="text-button logout" onClick={()=>{setView('welcome');notify('You’ve left the demo account.');}}><Icon name="exit" size={17}/> Leave demo account</button></section></main>:view==='sessions'?<main className="simple-page"><div className="eyebrow">ONE CONVERSATION AT A TIME</div><h1>Your practice, remembered.</h1><p className="muted">Simulated sessions from this visit. Refreshing clears this list.</p>{sessions.length===0?<div className="empty-state sessions-empty"><Icon name="clock" size={38}/><h3>Your first hello is waiting.</h3><p>Complete a demo call to see its recap here.</p><button className="primary" onClick={()=>setView('partners')}>Find a partner <Icon name="arrow"/></button></div>:<div className="session-list">{sessions.map(s=><article key={s.id}><span className="completion-icon small"><Icon name="check"/></span><div><h3>{s.name}</h3><p>Simulated practice session</p></div><strong>{formatDuration(s.seconds)}</strong></article>)}</div>}</main>:<main className="welcome-page"><div className="welcome-copy"><span className="eyebrow">WELCOME TO LINGUACONNECT</span><h1>A new language.<br/>A new <em>connection.</em></h1><p>Practice with people who are learning, just like you. A little courage and a simple hello are all it takes.</p><div className="welcome-points"><span><Icon name="users"/>Friendly conversation partners</span><span><Icon name="mic"/>Voice-first language practice</span><span><Icon name="shield"/>Go at your own pace</span></div></div><section className="welcome-form"><h2>Let’s meet you.</h2><p className="muted">Create a demo profile. No password or real account needed.</p><ProfileForm profile={profile} onboarding onSave={p=>{setProfile(p);setView('partners');notify('Welcome! Your demo profile is ready.');}}/></section></main>}
   </div>
  </div>
  {dialog==='language'&&<Modal title="What would you like to practice?" onClose={()=>setDialog(null)}><p className="muted">Choose a language for your next conversation.</p><div className="language-options">{(['English','Spanish'] as Language[]).map(lang=><button key={lang} className={profile.language===lang?'selected':''} onClick={()=>changeLanguage(lang)}><span className="language-code">{lang==='English'?'EN':'ES'}</span><span><strong>{lang}</strong><small>{selectPeople(lang,'Everyone','','All interests',blocked).length} sample profiles</small></span>{profile.language===lang&&<Icon name="check"/>}</button>)}</div></Modal>}
  {dialog==='scenarios'&&<Modal title="Explore the prototype" onClose={()=>setDialog(null)}><p className="muted">Try the main flow and see how it handles interruptions. No real calls or accounts are created.</p><label>Next outgoing call<select value={scenario} onChange={e=>setScenario(e.target.value as Scenario)}><option value="normal">Connect successfully</option><option value="denied">Microphone permission denied</option><option value="busy">Partner is busy</option><option value="timeout">Connection times out (6 seconds)</option></select></label><div className="scenario-check"><label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/> Show empty partner list</label><label><input type="checkbox" checked={offline} onChange={e=>setOffline(e.target.checked)}/> Show offline connection</label></div><button className="secondary full" onClick={()=>{setDialog(null);startCall(people[0],true);}}>Preview an incoming call <Icon name="phone" size={16}/></button><div className="button-row"><button className="text-button" onClick={reset}>Reset demo</button><button className="primary" onClick={()=>setDialog(null)}>Apply & explore</button></div></Modal>}
  {selected&&<Modal title="Meet your conversation partner" onClose={()=>setSelected(null)}><div className="profile-detail"><Avatar initials={selected.initials} color={selected.color} large/><h2>{selected.name}</h2><p className="muted">{selected.city}, {selected.country} · Sample profile</p><div className="profile-language">Native {selected.native} <span>Practices {profile.language}</span></div><p>{selected.bio}</p><div className="interest-tags">{selected.interests.map(i=><span key={i}>{i}</span>)}</div><button className="primary full" onClick={()=>startCall(selected)}><Icon name="phone" size={18}/>Say hello</button><button className="text-button" onClick={()=>{setBlocked([...blocked,selected.id]);setSelected(null);notify('Sample profile hidden. Restore it from My profile.');}}>Hide this sample profile</button></div></Modal>}
 </div>;
}
function ProfileForm({profile,onSave,onboarding=false}:{profile:DemoProfile;onSave:(p:DemoProfile)=>void;onboarding?:boolean}){
 const [name,setName]=useState(profile.name);const [native,setNative]=useState(profile.native);const [language,setLanguage]=useState<Language>(profile.language);const [error,setError]=useState('');
 return <form className="profile-form" onSubmit={e=>{e.preventDefault();if(!name.trim()){setError('Please enter a name.');return;}setError('');onSave({name:name.trim(),native,language});}}><label>What should we call you?<input maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Your first name" autoComplete="off"/></label>{error&&<p className="error-text" role="alert">{error}</p>}<div className="form-columns"><label>I speak<select value={native} onChange={e=>setNative(e.target.value)}>{['Spanish','English','French','Portuguese','German','Italian','Japanese','Mandarin','Other'].map(l=><option key={l}>{l}</option>)}</select></label><label>I’m practicing<select value={language} onChange={e=>setLanguage(e.target.value as Language)}><option>English</option><option>Spanish</option></select></label></div><button className="primary" type="submit">{onboarding?'Start exploring':'Save demo profile'}<Icon name="arrow" size={18}/></button></form>;
}
